# =========================================
# Docker Compose 開発環境設定ファイル
# NAFP Stack (Nginx + Angular + FastAPI + PostgreSQL)
# =========================================

services:
  # =========================================
  # PostgreSQLデータベースサービス
  # =========================================
  postgres:
    # 開発用Dockerfileを使用
    build:
      context: ..
      dockerfile: dockerfiles/postgres/dev/Dockerfile
    container_name: nafp_postgres_dev
    # 環境変数ファイルの読み込み
    env_file:
      - ../.envs/postgres/dev
    # ボリュームマウント設定
    volumes:
      # データ永続化用のボリューム
      - postgres_data:/var/lib/postgresql/data
      # 初期化スクリプト用（必要に応じて）
      - ../postgres/init:/docker-entrypoint-initdb.d
    # ポートマッピング（ホスト:コンテナ）
    ports:
      - "5432:5432"
    # ネットワーク設定
    networks:
      - nafp_network
    # ヘルスチェック設定
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nafp_user -d nafp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================================
  # FastAPI バックエンドサービス
  # =========================================
  fastapi:
    # 開発用Dockerfileを使用
    build:
      context: ..
      dockerfile: dockerfiles/fastapi/dev/Dockerfile
    container_name: nafp_fastapi_dev
    # 環境変数ファイルの読み込み
    env_file:
      - ../.envs/fastapi/dev
      - ../.envs/postgres/dev
    # ボリュームマウント設定（ホットリロード用）
    volumes:
      # ソースコードのマウント（開発時の変更を即座に反映）
      - ../fastapi:/app
      # Pythonキャッシュを除外
      - /app/__pycache__
    # ポートマッピング
    ports:
      - "8000:8000"
    # 依存関係の設定（PostgreSQLが起動してから起動）
    depends_on:
      postgres:
        condition: service_healthy
    # ネットワーク設定
    networks:
      - nafp_network
    # 開発用コマンド（ホットリロード有効）
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # =========================================
  # Angular フロントエンドサービス
  # =========================================
  angular:
    # 開発用Dockerfileを使用
    build:
      context: ..
      dockerfile: dockerfiles/angular/dev/Dockerfile
    container_name: nafp_angular_dev
    # 環境変数ファイルの読み込み
    env_file:
      - ../.envs/angular/dev
    # ボリュームマウント設定（ホットリロード用）
    volumes:
      # ソースコードのマウント
      - ../angular:/app
      # node_modulesを除外（パフォーマンス向上）
      - /app/node_modules
    # ポートマッピング
    ports:
      - "4440:4200"
    # 依存関係の設定
    depends_on:
      - fastapi
    # ネットワーク設定
    networks:
      - nafp_network
    # 開発用コマンド（ホットリロード有効）
    command: npm start

  # =========================================
  # Nginx リバースプロキシサービス
  # =========================================
  nginx:
    # 開発用Dockerfileを使用
    build:
      context: ..
      dockerfile: dockerfiles/nginx/dev/Dockerfile
    container_name: nafp_nginx_dev
    # ボリュームマウント設定
    volumes:
      # Nginx設定ファイルのマウント
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
    # ポートマッピング（メインのエントリーポイント）
    ports:
      - "80:80"
      - "443:443"
    # 依存関係の設定（全サービスが起動してから起動）
    depends_on:
      - angular
      - fastapi
    # ネットワーク設定
    networks:
      - nafp_network

# =========================================
# ネットワーク定義
# =========================================
networks:
  nafp_network:
    driver: bridge
    # カスタムネットワークでサービス間通信を簡単に

# =========================================
# ボリューム定義
# =========================================
volumes:
  postgres_data:
    # PostgreSQLデータの永続化
    driver: local
